const conf = {
  APPWRITE_URL: import.meta.env.VITE_APPWRITE_URL,
  APPWRITE_PROJECT_ID: import.meta.env.VITE_APPWRITE_PROJECT_ID,
  APPWRITE_DATABASE_ID: import.meta.env.VITE_APPWRITE_DATABASE_ID,
  APPWRITE_COLLECTION_ID: import.meta.env.VITE_APPWRITE_COLLECTION_ID,
  APPWRITE_BUCKET: import.meta.env.VITE_APPWRITE_BUCKET,
};

export default conf;
